### ISSUE TITLE
dpoPool_create user=sys extAuth=0: ORA-28009: connection as SYS should be as SYSDBA or SYSOPER

### ISSUE THREAD

**Issue by uknowsec** [Hel10-Web/Databasetools#11]
当用户名是sys时，报下面的错误
dpoPool_create user=sys extAuth=0: ORA-28009: connection as SYS should be as SYSDBA or SYSOPER

**Comment by 189er** [comment]
Navicat连接Oracle as sysdba 
https://www.cnblogs.com/EricShen/p/14900770.html
